/**
 * Report Harvest Route
 *
 * Authenticated whitelisted users submit geo-tagged photo reports.
 * Photo stored in R2 with UUID-based key. Report enters as 'pending'.
 *
 * Security:
 * - withUser() middleware validates Bearer JWT (T-03-05)
 * - Whitelisted source check prevents non-trusted submissions (T-03-08)
 * - MIME type validation (image/jpeg, image/png, image/webp only) (T-03-06)
 * - File size limit 10MB (T-03-09)
 * - Coordinate range validation (T-03-07)
 * - All D1 queries via prepared statements with .bind()
 */

import { Hono } from 'hono';
import type { Env } from '../lib/types';
import { withUser } from '../middleware/auth';
import type { AuthVariables } from '../middleware/auth';
import { createReport, getWhitelistedSourceByUserId } from '../lib/queries';

export const reportRoutes = new Hono<{
  Bindings: Env;
  Variables: AuthVariables;
}>();

const ALLOWED_MIME_TYPES = ['image/jpeg', 'image/png', 'image/webp'] as const;
const MAX_FILE_SIZE = 10 * 1024 * 1024; // 10MB

reportRoutes.post('/harvest', withUser(), async (c) => {
  const user = c.get('user');

  // T-03-08: Whitelisted source verification (D-02)
  const source = await getWhitelistedSourceByUserId(c.env.DB, user.id);
  if (!source) {
    return c.json({ error: 'User is not a whitelisted source' }, 403);
  }

  // Parse multipart body via standard Web API FormData
  const formData = await c.req.raw.formData();

  // T-03-06: Validate media (D-03)
  const media = formData.get('media');
  if (!media || !(media instanceof File)) {
    return c.json({ error: 'Missing media file' }, 400);
  }

  if (!ALLOWED_MIME_TYPES.includes(media.type as (typeof ALLOWED_MIME_TYPES)[number])) {
    return c.json(
      {
        error: `Invalid media type: ${media.type}. Allowed: ${ALLOWED_MIME_TYPES.join(', ')}`,
      },
      400
    );
  }

  // T-03-09: File size check
  if (media.size > MAX_FILE_SIZE) {
    return c.json(
      {
        error: `File too large: ${media.size} bytes. Max: ${MAX_FILE_SIZE} bytes`,
      },
      400
    );
  }

  // T-03-07: Validate coordinates
  const latStr = formData.get('latitude');
  const lonStr = formData.get('longitude');

  if (!latStr) {
    return c.json({ error: 'Missing latitude' }, 400);
  }
  if (!lonStr) {
    return c.json({ error: 'Missing longitude' }, 400);
  }

  const latitude = parseFloat(latStr as string);
  const longitude = parseFloat(lonStr as string);

  if (isNaN(latitude) || latitude < -90 || latitude > 90) {
    return c.json(
      { error: 'Invalid latitude: must be number between -90 and 90' },
      400
    );
  }
  if (isNaN(longitude) || longitude < -180 || longitude > 180) {
    return c.json(
      { error: 'Invalid longitude: must be number between -180 and 180' },
      400
    );
  }

  // RPT-03: Upload to R2 with UUID key
  const objectKey = `harvest/${crypto.randomUUID()}-${media.name}`;
  await c.env.VAULT.put(objectKey, await media.arrayBuffer());

  // RPT-02 + RPT-04: Create report (DIGIPIN auto-generated by createReport, status defaults to 'pending')
  const report = await createReport(c.env.DB, {
    reporterId: user.id,
    latitude,
    longitude,
    r2ImageUrl: `r2://${objectKey}`,
    status: 'pending',
  });

  return c.json({ report }, 201);
});
